apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: decisive-tahr-go 
  janus-idp.io/tekton: decisive-tahr-go
  backstage.io/kubernetes-id: decisive-tahr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: decisive-tahr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  