apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: decisive-tahr-go-gitops
  description: This is GitOps manifest for decisive-tahr-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: decisive-tahr-go
    janus-idp.io/tekton: decisive-tahr-go 
    backstage.io/kubernetes-id: decisive-tahr-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:decisive-tahr-go
