apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: decisive-tahr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: decisive-tahr-go 
  name: decisive-tahr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: decisive-tahr-go 
